version: '4'
services:
  postgresql:
    image: postgres:16.2
    container_name: sympoll-db-poll-test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
      - ./data:/data/db
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql